### ISSUE TITLE
version 0.7.6 doesn't work

### ISSUE THREAD

**Issue by Zhenshan-Jin** [keleshev/schema#310] opened 2024-03-26 19:59 UTC
after installation `schema==0.7.6`, schema can't be imported in python anymore with error 
```
In [1]: import schema
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import schema

ModuleNotFoundError: No module named 'schema'
```

python version: 3.10.6

**Comment by skorokithakis** [comment] 2024-03-26 20:01
Duplicate of #309

**Closed by skorokithakis** 2024-03-26 20:01 UTC
